version: "3.9"

services:
  srsenb:
    image: andriibond777/srsran
    container_name: srsenb
    network_mode: host
    cap_add:
      - SYS_NICE
    command: srsenb
      --enb.mme_addr=10.0.2.1
      --enb.gtp_bind_addr=10.0.2.2
      --enb.s1c_bind_addr=10.0.2.2
      --rf.device_name=zmq
      --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6"
      --log.all_level=debug

  srsue:
    image: andriibond777/srsran
    container_name: srsue
    network_mode: host
    depends_on:
      - srsenb
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    command: srsue
      --usim.algo=milenage
      --usim.imsi=999990000000002
      --usim.k=00112233445566778899aabbccddeeff
      --usim.opc=63BFA50EE6523365FF14C1F45F88737D
      --rf.device_name=zmq
      --rf.device_args="tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6"
      --gw.netns=ue1
      --log.all_level=debug
